"""
Context injector for generic agent integration.

Generates system prompt injection blocks that give any LLM agent
company-specific context from the KORE knowledge store.

Supports multiple output formats: markdown, xml, plain.
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import Literal

from memory.store import load_memory_store, query_memory


OutputFormat = Literal["markdown", "xml", "plain"]


def _format_entry_markdown(
    index: int,
    entry,
) -> list[str]:
    """Format a single memory entry as markdown lines."""
    source_str = " | ".join(entry.source_ids[:3]) if entry.source_ids else "unknown"
    return [
        f"### [{index}] {entry.entry_type.upper()}",
        f"- **Confidence**: {entry.confidence:.2f}",
        f"- **Freshness**: {entry.freshness:.2f}",
        f"- **Source**: {source_str}",
        "",
        f"{entry.content}",
        "",
    ]


def _format_entry_xml(
    index: int,
    entry,
) -> list[str]:
    """Format a single memory entry as XML lines."""
    source_str = " | ".join(entry.source_ids[:3]) if entry.source_ids else "unknown"
    return [
        f'  <entry index="{index}" type="{entry.entry_type}">',
        f'    <confidence>{entry.confidence:.2f}</confidence>',
        f'    <freshness>{entry.freshness:.2f}</freshness>',
        f'    <source>{source_str}</source>',
        f'    <content><![CDATA[{entry.content}]]></content>',
        "  </entry>",
    ]


def _format_entry_plain(
    index: int,
    entry,
) -> list[str]:
    """Format a single memory entry as plain text lines."""
    source_str = " | ".join(entry.source_ids[:3]) if entry.source_ids else "unknown"
    return [
        f"[{index}] {entry.entry_type.upper()} — confidence={entry.confidence:.2f} freshness={entry.freshness:.2f}",
        f"Source: {source_str}",
        f"Content: {entry.content}",
        "",
    ]


def _wrap_context(
    lines: list[str],
    format: OutputFormat,
    task_domain: str,
) -> str:
    """Wrap formatted lines in the chosen output envelope."""
    if format == "markdown":
        header = [
            f"# Company Knowledge Context — {task_domain}",
            "",
            f"> Auto-generated by KORE on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "The following rules, policies, and procedures are specific to this company. "
            "You must follow them when answering questions or taking actions related to this domain.",
            "",
            "---",
            "",
        ]
        return "\n".join(header + lines)

    if format == "xml":
        header = [
            f'<?xml version="1.0" encoding="UTF-8"?>',
            f'<company-knowledge domain="{task_domain}" generated="{datetime.now(timezone.utc).isoformat()}">',
            f'  <instruction>',
            f'    The following rules, policies, and procedures are specific to this company.',
            f'    You must follow them when answering questions or taking actions.',
            f'  </instruction>',
        ]
        footer = [
            "</company-knowledge>",
        ]
        return "\n".join(header + lines + footer)

    # plain
    header = [
        f"COMPANY KNOWLEDGE CONTEXT — {task_domain}",
        f"Generated: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
        "",
        "The following rules, policies, and procedures are specific to this company.",
        "You must follow them when answering questions or taking actions.",
        "",
        "-" * 40,
        "",
    ]
    return "\n".join(header + lines)


def generate_system_prompt_injection(
    task_domain: str,
    max_tokens: int = 1500,
    output_format: OutputFormat = "markdown",
) -> str:
    """Build a company knowledge context block for agent system prompts.

    Parameters
    ----------
    task_domain : str
        Natural language description of the task domain (e.g. "refund policy",
        "deployment process", "pricing rules").
    max_tokens : int
        Approximate token budget. ~4 chars per token.
    output_format : str
        One of "markdown", "xml", "plain".

    Returns
    -------
    str
        Formatted context block ready to prepend to a system prompt.
    """
    store = load_memory_store("memory/store.json")
    if not store.entries:
        return ""

    entries = query_memory(task_domain, store, top_k=10)
    if not entries:
        return ""

    char_budget = max_tokens * 4

    # Choose formatter
    formatters = {
        "markdown": _format_entry_markdown,
        "xml": _format_entry_xml,
        "plain": _format_entry_plain,
    }
    formatter = formatters[output_format]

    lines: list[str] = []
    current_chars = 0

    for i, entry in enumerate(entries, 1):
        entry_lines = formatter(i, entry)
        entry_chars = sum(len(line) for line in entry_lines)
        if current_chars + entry_chars > char_budget:
            if output_format == "xml":
                lines.append('  <entry truncated="true"/>')
            else:
                lines.append("[truncated]")
            break
        lines.extend(entry_lines)
        current_chars += entry_chars

    return _wrap_context(lines, output_format, task_domain)


def export_context_file(
    task_domain: str,
    output_path: str = "kore_context.md",
    output_format: OutputFormat = "markdown",
    max_tokens: int = 1500,
) -> str:
    """Generate a context injection block and write it to a file.

    Returns the absolute path to the written file.
    """
    content = generate_system_prompt_injection(
        task_domain=task_domain,
        max_tokens=max_tokens,
        output_format=output_format,
    )

    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")

    return str(path.resolve())
