"""Unit tests for integrations/context_injector.py"""

import json
from datetime import datetime, timezone
from pathlib import Path
from unittest.mock import patch

import pytest

from integrations.context_injector import (
    generate_system_prompt_injection,
    export_context_file,
    _format_entry_markdown,
    _format_entry_xml,
    _format_entry_plain,
    _wrap_context,
)
from memory.store import MemoryEntry, MemoryStore


# ---------------------------------------------------------------------------
# Internal formatter tests
# ---------------------------------------------------------------------------


class TestFormatEntryMarkdown:
    def test_includes_confidence_and_freshness(self):
        entry = MemoryEntry(
            content="Refund within 7 days",
            entry_type="rule",
            confidence=0.95,
            freshness=0.92,
            source_ids=["rule-1"],
        )
        lines = _format_entry_markdown(1, entry)
        text = "\n".join(lines)
        assert "### [1] RULE" in text
        assert "0.95" in text
        assert "0.92" in text
        assert "rule-1" in text
        assert "Refund within 7 days" in text


class TestFormatEntryXml:
    def test_includes_cdata_and_attributes(self):
        entry = MemoryEntry(
            content="Special <chars> & stuff",
            entry_type="rule",
            confidence=0.95,
            freshness=0.92,
            source_ids=["rule-1"],
        )
        lines = _format_entry_xml(1, entry)
        text = "\n".join(lines)
        assert '<entry index="1" type="rule">' in text
        assert "<confidence>0.95</confidence>" in text
        assert "<![CDATA[Special <chars> & stuff]]>" in text


class TestFormatEntryPlain:
    def test_includes_all_fields(self):
        entry = MemoryEntry(
            content="Plain text rule",
            entry_type="rule",
            confidence=0.95,
            freshness=0.92,
            source_ids=["rule-1"],
        )
        lines = _format_entry_plain(1, entry)
        text = "\n".join(lines)
        assert "[1] RULE" in text
        assert "confidence=0.95" in text
        assert "Plain text rule" in text


class TestWrapContext:
    def test_markdown_header(self):
        result = _wrap_context(["line"], "markdown", "pricing")
        assert "# Company Knowledge Context — pricing" in result
        assert "Auto-generated by KORE" in result

    def test_xml_header(self):
        result = _wrap_context(["  <entry/>"], "xml", "pricing")
        assert '<?xml version="1.0"' in result
        assert '<company-knowledge domain="pricing"' in result

    def test_plain_header(self):
        result = _wrap_context(["line"], "plain", "pricing")
        assert "COMPANY KNOWLEDGE CONTEXT — pricing" in result


# ---------------------------------------------------------------------------
# generate_system_prompt_injection tests
# ---------------------------------------------------------------------------


class TestGenerateSystemPromptInjection:
    @patch("integrations.context_injector.load_memory_store")
    @patch("integrations.context_injector.query_memory")
    def test_markdown_output(self, mock_query, mock_load):
        store = MemoryStore(
            entries=[
                MemoryEntry(
                    content="Refund within 7 days",
                    entry_type="rule",
                    confidence=0.95,
                    freshness=0.92,
                    embedding=[0.1, 0.2],
                    source_ids=["rule-1"],
                )
            ]
        )
        mock_load.return_value = store
        mock_query.return_value = store.entries

        result = generate_system_prompt_injection("refund policy", max_tokens=500, output_format="markdown")
        assert "# Company Knowledge Context — refund policy" in result
        assert "Refund within 7 days" in result
        assert "0.95" in result

    @patch("integrations.context_injector.load_memory_store")
    @patch("integrations.context_injector.query_memory")
    def test_xml_output(self, mock_query, mock_load):
        store = MemoryStore(
            entries=[
                MemoryEntry(
                    content="Refund within 7 days",
                    entry_type="rule",
                    confidence=0.95,
                    freshness=0.92,
                    embedding=[0.1, 0.2],
                    source_ids=["rule-1"],
                )
            ]
        )
        mock_load.return_value = store
        mock_query.return_value = store.entries

        result = generate_system_prompt_injection("refund policy", max_tokens=500, output_format="xml")
        assert '<?xml version="1.0"' in result
        assert "<company-knowledge" in result
        assert "<entry" in result

    @patch("integrations.context_injector.load_memory_store")
    @patch("integrations.context_injector.query_memory")
    def test_plain_output(self, mock_query, mock_load):
        store = MemoryStore(
            entries=[
                MemoryEntry(
                    content="Refund within 7 days",
                    entry_type="rule",
                    confidence=0.95,
                    freshness=0.92,
                    embedding=[0.1, 0.2],
                    source_ids=["rule-1"],
                )
            ]
        )
        mock_load.return_value = store
        mock_query.return_value = store.entries

        result = generate_system_prompt_injection("refund policy", max_tokens=500, output_format="plain")
        assert "COMPANY KNOWLEDGE CONTEXT" in result
        assert "Refund within 7 days" in result

    @patch("integrations.context_injector.load_memory_store")
    def test_empty_store_returns_empty(self, mock_load):
        mock_load.return_value = MemoryStore()
        result = generate_system_prompt_injection("refund policy")
        assert result == ""

    @patch("integrations.context_injector.load_memory_store")
    @patch("integrations.context_injector.query_memory")
    def test_empty_query_returns_empty(self, mock_query, mock_load):
        mock_load.return_value = MemoryStore(
            entries=[MemoryEntry(content="rule", entry_type="rule", confidence=0.9, embedding=[0.1])]
        )
        mock_query.return_value = []
        result = generate_system_prompt_injection("refund policy")
        assert result == ""

    @patch("integrations.context_injector.load_memory_store")
    @patch("integrations.context_injector.query_memory")
    def test_truncation_respected(self, mock_query, mock_load):
        long_text = "A" * 1000
        store = MemoryStore(
            entries=[
                MemoryEntry(
                    content=long_text,
                    entry_type="rule",
                    confidence=0.95,
                    freshness=0.92,
                    embedding=[0.1, 0.2],
                )
            ]
        )
        mock_load.return_value = store
        mock_query.return_value = store.entries

        result = generate_system_prompt_injection("refund policy", max_tokens=50, output_format="markdown")
        assert "[truncated]" in result


# ---------------------------------------------------------------------------
# export_context_file tests
# ---------------------------------------------------------------------------


class TestExportContextFile:
    @patch("integrations.context_injector.load_memory_store")
    @patch("integrations.context_injector.query_memory")
    def test_writes_file_and_returns_path(self, mock_query, mock_load, tmp_path):
        store = MemoryStore(
            entries=[
                MemoryEntry(
                    content="Refund within 7 days",
                    entry_type="rule",
                    confidence=0.95,
                    freshness=0.92,
                    embedding=[0.1, 0.2],
                    source_ids=["rule-1"],
                )
            ]
        )
        mock_load.return_value = store
        mock_query.return_value = store.entries

        out = tmp_path / "context.md"
        path = export_context_file("refund policy", output_path=str(out), output_format="markdown")
        assert Path(path).exists()
        content = Path(path).read_text(encoding="utf-8")
        assert "Refund within 7 days" in content
        assert "# Company Knowledge Context" in content

    @patch("integrations.context_injector.load_memory_store")
    @patch("integrations.context_injector.query_memory")
    def test_creates_parent_dirs(self, mock_query, mock_load, tmp_path):
        store = MemoryStore(
            entries=[
                MemoryEntry(
                    content="Test",
                    entry_type="rule",
                    confidence=0.9,
                    freshness=0.9,
                    embedding=[0.1],
                )
            ]
        )
        mock_load.return_value = store
        mock_query.return_value = store.entries

        out = tmp_path / "deep" / "nested" / "context.md"
        path = export_context_file("test", output_path=str(out))
        assert Path(path).exists()
